# -*- coding: utf-8 -*-
"""Advanced_RAG_GLHF_Code final for libre office.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjcZcAAoJqakklTeVttcyLmosHiNNVyG
"""

!pip install -qU langchain_experimental langchain_openai langchain_community langchain ragas chromadb langchain-groq fastembed pypdf openai

!pip install h5py
!pip install typing-extensions
!pip install wheel

from langchain.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

loader = PyPDFLoader("COMBINED_DOCUMENT.pdf")

documents = loader.load()
#print(len(documents))

'''from langchain.text_splitter import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=0,
    length_function=len,
    is_separator_regex=False
)#use semantic chunking istead of this

#
naive_chunks = text_splitter.split_documents(documents)
for chunk in naive_chunks[10:74]:
  print(chunk.page_content+ "\n")'''

#from langchain_community.embeddings.fastembed import FastEmbedEmbeddings
#embed_model = FastEmbedEmbeddings()
!pip install langchain-huggingface
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
embed_model = HuggingFaceEmbeddings()

"""# Modification - Souvik"""

from langchain.document_loaders import PyPDFLoader

loader = PyPDFLoader("COMBINED_DOCUMENT.pdf")
acss_pages = loader.load_and_split()

from langchain.vectorstores import Chroma
from langchain.text_splitter import RecursiveCharacterTextSplitter

from langchain.chains import RetrievalQA
from langchain.document_loaders import TextLoader
from langchain.document_loaders import PyPDFLoader
from langchain.document_loaders import DirectoryLoader

text_splitter = RecursiveCharacterTextSplitter(chunk_size=5000, chunk_overlap=500)
acss_texts = text_splitter.split_documents(acss_pages)

persist_directory = 'acss_cfp'

## Here is the nmew embeddings being used
embedding = embed_model

acss_cfp_vectordb = Chroma.from_documents(documents=acss_texts,
                                 embedding=embedding,
                                 persist_directory=persist_directory)

def retrieve_relevant_docs(user_query):
  retriever = acss_cfp_vectordb.as_retriever(search_type="mmr", search_kwargs={"k": 5})#search_type="similar"
  results = retriever.invoke(user_query)
  searched_content = []
  for result in results:
      #print(result.page_content)
      searched_content.append(result.page_content)

  combined_content = " ".join(searched_content)

  # Print or use the combined string
  # print(combined_content)
  return combined_content

"""# **mistralai/Mixtral-8x22B-Instruct-v0.1**"""

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
               1.Can you find the association between the user query and the given context?
               2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
               3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
               If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:mistralai/Mixtral-8x22B-Instruct-v0.1",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_11.csv'
output_csv_path = 'output_responses_11.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_11.csv')



import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_11.csv'
output_csv_path = 'output_responses_11.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_11.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_22c6da6cab76808699698f97ef6a1c89",
        base_url="https://glhf.chat/api/openai/v1",#glhf_tint_code
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_7.csv'
output_csv_path = 'output_responses_7.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_7.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_39192d9a302353fd6b50f33c1b5cd837",
        base_url="https://glhf.chat/api/openai/v1",#glhy_Chin
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_8.csv'
output_csv_path = 'output_responses_8.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_8.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_7dc4654582dbd29df00ffcdd01023db1",
        base_url="https://glhf.chat/api/openai/v1",#glhf_
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_9.csv'
output_csv_path = 'output_responses_9.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_9.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_5795d69a68acc820bf29dfe11e3de66a",
        base_url="https://glhf.chat/api/openai/v1",#glhf_Tap
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_10.csv'
output_csv_path = 'output_responses_10.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_10.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_11.csv'
output_csv_path = 'output_responses_11.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_11.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_803cc673aebee950ab0b3bbb43095498",
        base_url="https://glhf.chat/api/openai/v1",#glhf_Tap
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_3.csv'
output_csv_path = 'output_responses_3.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_3.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_5795d69a68acc820bf29dfe11e3de66a",
        base_url="https://glhf.chat/api/openai/v1",#glhf_Tap
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_4.csv'
output_csv_path = 'output_responses_4.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_4.csv')

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )
    cot_prompt = """
             From the given context and the user query can you answer the following questions.
            1.Can you find the association between the user query and the given context?
            2.Can you find the relevant feature that may encounter the issues or concerns presented in the user query?
            3.Your final response will be only the product feature that can be mapped to the concerns of the user query. Also provide the justification.
            If you cannot answer them properly, please respond with 'I don't know'.
            """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            user_query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            combined_content = retrieve_relevant_docs(user_query)

            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {combined_content}"},
                    {"role": "user", "content": f"Here is the {user_query + cot_prompt}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([user_query, response])
            print(f"Processed query: {user_query}")

# Example usage:
input_csv_path = 'input_480_5.csv'
output_csv_path = 'output_responses_5.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_5.csv')

from google.colab import drive
drive.mount('/content/drive')

# acss_cfp_retriever = acss_cfp_vectordb.as_retriever(search_kwargs={"k": 5})
retriever = acss_cfp_vectordb.as_retriever(search_type="similarity", search_kwargs={"k": 5})
results = retriever.invoke("What is the product feature mapping to 'Calc does not allow me to write 'LScaleVPN' to a cell, saves 'LscaleVPN''?")

searched_content = []
for result in results:
    print(result.page_content)
    searched_content.append(result.page_content)

combined_content = " ".join(searched_content)

# Print or use the combined string
print(combined_content)

import os
import openai

client = openai.OpenAI(
  api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
  base_url="https://glhf.chat/api/openai/v1",
)

'''completion = client.chat.completions.create(
    model="hf:Nexusflow/Athene-V2-Chat",
    messages=[
        {"role": "system", "content": "You are a helpful assistant. You will help me to map the {user} query to a product feature."},
        {"role": "assistant", "content": f"Here is some context: {combined_content}"},
        {"role": "user", "content": "What is the product feature mapping to Date values from registered database appear as numbers when using them in a Pivot table data?"}
    ]
)

# Extract and print the response

print(completion.choices[0].message)
# print(completion.choices[0].message)'''#for single use test

#print(completion.choices[0].message.content)

#print(combined_content)

"""**Not required , Previous Code**"""

#pip install langchain
#pip install glhf
'''import os
import openai

client = openai.OpenAI(
  api_key=os.environ.get("glhf_"),
  base_url="https://glhf.chat/api/openai/v1",
)'''
import os
os.environ["OPENAI_API_KEY"] = "openai_glhf"  # Replace with your key
import openai

client = openai.OpenAI(
    # The API key will now be picked up automatically
    base_url="https://glhf.chat/api/openai/v1",  # Keep your base URL
)

#!pip install -q -U langchain langchain_core langchain_groq gradio

!pip install -q -U langchain langchain_core together

!pip install langchain-together

from google.colab import userdata
!pip install -q -U langchain langchain_core
#from langchain_together.llms import Together

#together_api_key = userdata.get("TOGETHER")

#groq_api_key = userdata.get("final")

from langchain_experimental.text_splitter import SemanticChunker
from langchain_openai.embeddings import OpenAIEmbeddings

!pip install -q -U fastembed

semantic_chunker = SemanticChunker(embed_model, breakpoint_threshold_type="percentile")
#
semantic_chunks = semantic_chunker.create_documents([d.page_content for d in documents])
#

for semantic_chunk in semantic_chunks:
  if "Effect of Pre-training Tasks" in semantic_chunk.page_content:
    print(semantic_chunk.page_content)
    print(len(semantic_chunk.page_content))

from langchain_community.vectorstores import Chroma
semantic_chunk_vectorstore = Chroma.from_documents(semantic_chunks, embedding=embed_model)

semantic_chunk_retriever = semantic_chunk_vectorstore.as_retriever(search_kwargs={"k" : 5})
#semantic_chunk_retriever.invoke("Describe the Feature-based Approach with BERT?")

from langchain_core.prompts import ChatPromptTemplate

rag_template = """\
Use the following {context} to map the issue in user {query} to a product feature listed in the {context}. If you cannot answer, please respond with 'I don't know'.

User's Query:
{query}

Context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(rag_template)

'''!pip install langchain-together

from langchain_together import Together

together_api_key = userdata.get("Raunak_Tog")  # Replace with your Together.ai API key

chat_model = Together(
    model="meta-llama/Meta-Llama-3-70B-Instruct-Lite",  # Choose a Together.ai model
    temperature=0,
    api_key=together_api_key,
    max_tokens=100,
)'''
api_key = os.environ.get("openai_glhf")
client = openai.OpenAI(api_key=api_key)

rag_template = """\
Use the following {context} to map the issue in user {query} to a product feature listed in the {context}. If you cannot answer, please respond with 'I don't know'.

User's Query:
{query}

Context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(rag_template)

messages = [
    {"role": "user", "content": rag_prompt.format(query="example query", context="example context")}
]

completion = client.chat.completions.create(
    model="meta-llama/Meta-Llama-3.1-405B-Instruct",
    messages=messages
)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

semantic_rag_chain = (
    {"context" : semantic_chunk_retriever, "query" : RunnablePassthrough()}
    | rag_prompt
    | model
    | StrOutputParser()
)

import csv
import time
from google.colab import files
def process_data(component, summary):
    # Combine all fields into a single string
    combined_string = f"Component: {component}, Summary: {summary}"
    return(combined_string)

# Open the CSV file
with open('1_final_libre_office.csv', 'r', encoding='latin-1') as infile, open('output.csv', 'w', newline='') as outfile:
    reader = csv.DictReader(infile)
    writer = csv.writer(outfile)

    # Write header row if needed
    writer.writerow(["Query", "Result"])

    # Iterate over each row in the CSV file
    for row in reader:
        # Extract the data from the required fields
        #product = row['Product']
        component = row['Component']
        summary = row['Summary']
        #version = row['Version']

        # Pass the data to the function
        query= process_data(component, summary)
        result = semantic_rag_chain.invoke(query)
        writer.writerow([query, result])
        print("Processed query:", {query})
        time.sleep(3)
files.download('output.csv')

"""WRITE A CODE TO LOAD A CSV FILE , fetch one row at a time and place the value in the quotes in this semantic_rag_chain.invoke("") run the loop till the end and reset and 2 fetch"""

semantic_rag_chain.invoke("Allow modification of the order of fields.")

semantic_rag_chain.invoke("Deleting a chart based on a large dataset rather slow")

semantic_rag_chain.invoke("Automating Gap/Object Position Redistribution for Easier Aligning and Repositioning of Objects")

semantic_rag_chain.invoke("Calc Round Down is Rounding Up for some values")

import csv
from google.colab import files
def process_csv_and_save_results(input_filename, output_filename):
    with open(input_filename, 'r') as infile, open(output_filename, 'w', newline='') as outfile:
        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        # Write header row if needed
        writer.writerow(["Query", "Result"])  # Adjust header as needed

        for i in range(0,1508,1):#Skip to the second row
                  next(reader, None)

        #Iterate for 500 rows
        for i in range(500):
          try:
                row = next(reader)
                # Preprocess the query
                query = row[0].strip()
                query = query.replace('\n', ' ')

                result = semantic_rag_chain.invoke(query)

                # Write query and result to output CSV
                writer.writerow([query, result])

                print("Processed query:", {query})

          except StopIteration:
                print("Reached the end of the file.")
                break  # Exit the loop if there are no more rows

          except Exception as e:
                result = "ERROR"
                writer.writerow([query, result])
                print("ERROR")
                # You might want to log the error or handle it differently

# Example usage
process_csv_and_save_results('final_libre_office.csv', '5_final_results.csv')
files.download('4_final_results.csv')

'''import csv

def process_csv_and_save_results(input_filename, output_filename):
    with open(input_filename, 'r') as infile, open(output_filename, 'w', newline='') as outfile:
        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        # Write header row if needed
        writer.writerow(["Query", "Result"])  # Adjust header as needed

        for row in reader:
            try:
                # Preprocess the query
                query = row[0].strip()
                query = query.replace('\n', ' ')

                result = semantic_rag_chain.invoke(query)

                # Write query and result to output CSV
                writer.writerow([query, result])

                print("Processed query:", {query})

            except Exception as e:
                print("ERROR")
                # You might want to log the error or handle it differently

# Example usage
process_csv_and_save_results('Libre_office.csv', 'results.csv')'''

'''import csv

def process_csv(filename):
    with open(filename, 'r') as file:
        reader = csv.reader(file)
        # next(reader)  # Skip the header row if needed

        for row in reader:
            try:
                # Preprocess the query
                query = row[0].strip()
                query = query.replace('\n', ' ')

                result = semantic_rag_chain.invoke(query)
                print("This is a new query")
                print("Query:", {query}, "\n", "Result:", {result})

            except Exception as e:
                print(f"Error processing query: {query}")
                print(f"Error: {e}")
                # You might want to log the error or handle it differently

# Example usage
process_csv('Libre_office.csv')'''

'''import csv

def process_csv(filename):
  with open(filename, 'r') as file:
    reader = csv.reader(file)
    #next(reader)  # Skip the header row
    for row in reader:
      query = row[0]  # Assuming the query is in the first column
      result = semantic_rag_chain.invoke(query)
      print("This is a new query")
      print("Query:", {query},"\n","Result:",{result})

# Example usage
process_csv('Libre_office.csv')'''

'''from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

semantic_rag_chain = (
    {"context" : semantic_chunk_retriever, "query" : RunnablePassthrough()}
    | rag_prompt
    | chat_model
    | StrOutputParser()
)'''

semantic_rag_chain.invoke("Undo not working properly, blocking formatting of table cell")

'''from together import Together

# Initialize the Together client only with the API key.
chat_model = Together(api_key=together_api_key)

response = chat_model.completions.create(
    model="mistralai/Mistral-7B-v0.1",
    prompt=rag_template,
    temperature=0,
)'''

'''import os
from together import Together
chat_model = Together(
    model="mistralai/Mistral-7B-v0.1",  # Choose a Together.ai model
    temperature=0,
    api_key=together_api_key,
)
chat_model = ChatGroq(temperature=0,
                      model_name="mixtral-8x7b-32768",
                      api_key=userdata.get("final"),)'''

'''from langchain_core.runnables import RunnableLambda
from langchain.prompts.chat import ChatPromptValue# Create a runnable function that calls the Together API
def together_runnable(inputs):
    # If inputs is a ChatPromptValue, extract the prompt
    if isinstance(inputs, ChatPromptValue):
        prompt = inputs.messages[0].content  # Access the content of the first message
    # If inputs is a dictionary, access the prompt as before
    elif isinstance(inputs, dict):
        prompt = inputs["prompt"]
    else:
        raise TypeError("Unexpected input type: {}".format(type(inputs)))

    response = chat_model.completions.create(
        model="mistralai/Mistral-7B-v0.1",
        prompt=prompt,
        temperature=0,
    )
    return response.choices[0].text

semantic_rag_chain = (
    {"context": semantic_chunk_retriever, "query": RunnablePassthrough()}
    | rag_prompt
    | together_runnable  # Use the modified together_runnable function
    | StrOutputParser()
)'''

'''import pandas as pd
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
!pip install langchain-together

from langchain_together import Together

together_api_key = userdata.get("TOGETHER")
# Load queries from CSV file
queries_df = pd.read_csv("libre_office.csv")  # Assuming your queries are in 'queries.csv'
queries = queries_df["QUERY"].tolist()  # Assuming 'query' is the column name
# Function to initialize the model
def initialize_model():
    return Together(
        model="meta-llama/Meta-Llama-3-70B-Instruct-Lite",
        temperature=0,
        api_key=together_api_key,
        max_tokens=100,  # Adjust as needed
    )
# Function to initialize the model
def initialize_model():
    return Together(
        model="meta-llama/Meta-Llama-3-70B-Instruct-Lite",
        temperature=0,
        api_key=together_api_key,
        max_tokens=100,  # Adjust as needed
    )
# Define the chain
semantic_rag_chain = (
    {"context": semantic_chunk_retriever, "query": RunnablePassthrough()}
    | rag_prompt
    | chat_model
    | StrOutputParser()
)
# Initialize the results list before the loop
results = []  # This line is added to initialize the list
# Process queries and handle token maximization
for i, query in enumerate(queries):
    try:
        result = semantic_rag_chain.invoke(query)
        results.append({"query": query, "result": result})
    except ValueError as e:
        if "Input validation error" in str(e):
            print(f"Token limit reached for query {i}. Restarting model...")
            chat_model = initialize_model()  # Restart the model
            result = semantic_rag_chain.invoke(query)  # Retry the query
            results.append({"query": query, "result": result})
        else:
            print(f"Error processing query {i}: {e}")

# Store results in a CSV file
results_df = pd.DataFrame(results)
results_df.to_csv("results.csv", index=False)

print("Processing complete. Results saved to results.csv")'''