# -*- coding: utf-8 -*-
"""RAG GLHF  Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKOTTDlAO_X4NCYxOHgA3rscKNN5D7EL
"""

!pip install -qU langchain_experimental langchain_openai langchain_community langchain ragas chromadb langchain-groq fastembed pypdf openai

# import libraries
import os
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI

import csv
import openai
from google.colab import files
##OPENAI_API_KEY = os.getenv('OPENAI_API_KEY') ## add your OpenAI API Key
# for this example I used Alphabet Inc 10-K Report 2022
# https://www.sec.gov/Archives/edgar/data/1652044/000165204423000016/goog-20221231.htm
client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )

# ----- Data Indexing Process -----
from langchain.document_loaders import PyPDFLoader
# load your pdf doc
loader = PyPDFLoader("COMBINED_DOCUMENT.pdf")
pages = loader.load()
#DOC_PATH = "../alphabet_10K_2022.pdf"
CHROMA_PATH = "your_db_name"

# split the doc into smaller chunks i.e. chunk_size=500
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
chunks = text_splitter.split_documents(pages)

!pip install langchain-huggingface
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
embed_model = HuggingFaceEmbeddings()
embedding = embed_model

# embed the chunks as vectors and load them into the database
db_chroma = Chroma.from_documents(chunks, embedding, persist_directory=CHROMA_PATH)

# ----- Retrieval and Generation Process -----

# this is an example of a user question (query)
query = 'Many backups (like 1889 in 10 minutes) automatically created while editing queries in SQL-view'

# retrieve context - top 5 most relevant (closests) chunks to the query vector
# (by default Langchain is using cosine distance metric)
docs_chroma = db_chroma.similarity_search_with_score(query, k=5)

# generate an answer based on given user query and retrieved context information
context_text = "\n\n".join([doc.page_content for doc, _score in docs_chroma])

import csv
import openai
from google.colab import files

def process_queries_from_csv(input_csv_path, output_csv_path):
    """
    Processes user queries from an input CSV file, sends them to the OpenAI API,
    and stores the responses in an output CSV file.

    Args:
        input_csv_path: Path to the input CSV file containing user queries.
        output_csv_path: Path to the output CSV file where responses will be stored.
        combined_content: The context to be passed to the OpenAI API.

    Returns:
        None
    """

    client = openai.OpenAI(
        api_key="glhf_d70b0e7476fb6abd42da42fed917c80f",
        base_url="https://glhf.chat/api/openai/v1",#glhf_anand
    )
    # you can use a prompt template
    PROMPT_TEMPLATE = """\
    Use the following {context} to map the issue in user {query} to a product feature listed in the {context}. If you cannot answer, please respond with 'I don't know'.

    User's Query:
    {query}

    Context:
    {context}
    """
    with open(input_csv_path, 'r', encoding='latin-1') as infile, open(output_csv_path, 'w', newline='', encoding='utf-8') as outfile: # Changed encoding to latin-1 for infile and utf-8 for outfile
        reader = csv.DictReader(infile)
        writer = csv.writer(outfile)
        writer.writerow(["Query", "Response"])  # Write header row

        # Skip header row if it exists
        #next(reader, None)

        for row in reader:
            component = row['Component']
            user_query = row['Summary']
            query =  " Component of the product is " + component+ " and the user query is " + user_query
            #component = row[0]
            #user_query = row[1]  # Assuming query is in the first column
            context_text = "\n\n".join([doc.page_content for doc, _score in docs_chroma])
            # load retrieved context and user query in the prompt template
            prompt_template = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)
            prompt = prompt_template.format(context=context_text, query=query)
            completion = client.chat.completions.create(
                model="hf:meta-llama/Llama-3.3-70B-Instruct",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {context_text}"},
                    {"role": "user", "content": f"Here is the {query + PROMPT_TEMPLATE}"}
                ]
            )

            response = completion.choices[0].message.content
            writer.writerow([query, response])
            print(f"Processed query: {query}")

# Example usage:
input_csv_path = 'input_480_11_1.csv'
output_csv_path = 'output_responses_11.csv'
process_queries_from_csv(input_csv_path, output_csv_path)
files.download('output_responses_11.csv')

# you can use a prompt template
PROMPT_TEMPLATE = """\
Use the following {context} to map the issue in user {query} to a product feature listed in the {context}. If you cannot answer, please respond with 'I don't know'.

User's Query:
{query}

Context:
{context}
"""

# load retrieved context and user query in the prompt template
prompt_template = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)
prompt = prompt_template.format(context=context_text, query=query)

# call LLM model to generate the answer based on the given context and query
#model = ChatOpenAI()
#response_text = model.predict(prompt)

completion = client.chat.completions.create(
                model="hf:mistralai/Mixtral-8x22B-Instruct-v0.1",
                messages=[
                    {"role": "system", "content": "You are a helpful assistant. Based on the given context answer the user query "},
                    {"role": "assistant", "content": f"Here is some context: {context_text}"},
                    {"role": "user", "content": f"Here is the {query + PROMPT_TEMPLATE}"}
                ]
            )

response = completion.choices[0].message.content

print(response)

'''# get OpenAI Embedding model
embeddings = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

# embed the chunks as vectors and load them into the database
db_chroma = Chroma.from_documents(chunks, embeddings, persist_directory=CHROMA_PATH)

# ----- Retrieval and Generation Process -----

# this is an example of a user question (query)
query = 'what are the top risks mentioned in the document?'

# retrieve context - top 5 most relevant (closests) chunks to the query vector
# (by default Langchain is using cosine distance metric)
docs_chroma = db_chroma.similarity_search_with_score(query, k=5)

# generate an answer based on given user query and retrieved context information
context_text = "\n\n".join([doc.page_content for doc, _score in docs_chroma])



"""
Generated response:

The top risks mentioned in the provided context are:
1. Decline in the value of investments
2. Lack of adoption of products and services
3. Interference or interruption from various factors such as modifications, terrorist attacks, natural disasters, etc.
4. Compromised trade secrets and legal and financial risks
5. Reputational, financial, and regulatory exposure
6. Abuse of platforms and misuse of user data
7. Errors or vulnerabilities leading to service interruptions or failure
8. Risks associated with international operations.
"""